### ISSUE TITLE
[FEAT] 상품 관련 로직 

### ISSUE THREAD

**Issue by juanxiu** [TEAM-PEDALGENIE/PedalGenie-Back#3]
## 📚 이슈 설명

상품 관련 로직 

---
## 📝 상세 설명
상품에 대한 로직을 구현합니다. 

---
## ✅ TO-DO 
- [x] 상위 카테고리 내 상품 조회 
- [x] 상품 상세 조회 
- [x] 옵션에 따라 상품 목록 조회 
- [x] 필터 옵션 조회 
- [x] 카테고리 옵션 조회
